// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:flutter/widgets.dart';
import 'package:routefly/routefly.dart';

import 'ui/auth/login/login_page.dart' as a0;
import 'ui/auth/registrar/registrar_page.dart' as a1;
import 'ui/auth/senha/esqueci_senha_page.dart' as a2;
import 'ui/carona/cadastro/cadastrar_carona_page.dart' as a3;
import 'ui/carona/carona_home_page.dart' as a4;
import 'ui/carona/visualizar/[id]/carona_page.dart' as a8;
import 'ui/carona/visualizar/carona_anterior_page.dart' as a6;
import 'ui/carona/visualizar/caronas_usuario_page.dart' as a5;
import 'ui/carona/visualizar/lista_carona_anterior_page.dart' as a7;
import 'ui/mensagem_page.dart' as a9;
import 'ui/rota/rota_page.dart' as a10;
import 'ui/usuario/cadastro/cadastrar_carro_page.dart' as a11;
import 'ui/usuario/cadastro/cadastrar_foto_page.dart' as a12;
import 'ui/usuario/cadastro/cadastrar_localizacao_page.dart' as a13;
import 'ui/usuario/cadastro/cadastrar_papel_page.dart' as a14;
import 'ui/usuario/editar/editar_carro_page.dart' as a15;
import 'ui/usuario/editar/editar_perfil_page.dart' as a16;

Route b0Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a0.LoginPage());
Route b1Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a1.RegistrarPage());
Route b2Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a2.EsqueciSenhaPage());
Route b3Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a3.CadastrarCaronaPage());
Route b4Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a4.CaronaHomePage());
Route b5Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a5.CaronasUsuarioPage());
Route b6Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a6.CaronaAnteriorPage());
Route b7Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a7.ListaCaronaAnteriorPage(),
    );
Route b8Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a8.CaronaPage());
Route b9Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a9.MensagemPage());
Route b10Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a10.RotaPage());
Route b11Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a11.CadastrarCarroPage());
Route b12Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a12.CadastrarFotoPage());
Route b13Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a13.CadastrarLocalizacaoPage(),
    );
Route b14Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a14.CadastrarPapelPage());
Route b15Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a15.EditarCarroPage());
Route b16Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a16.EditarPerfilPage());
