// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(
    key: 'auth/login',
    uri: Uri.parse('auth/login'),
    routeBuilder: b0Builder,
  ),
  RouteEntity(
    key: 'auth/registrar',
    uri: Uri.parse('auth/registrar'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(
    key: 'auth/senha/esqueci_senha',
    uri: Uri.parse('auth/senha/esqueci_senha'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(
    key: 'carona/cadastro/cadastrar_carona',
    uri: Uri.parse('carona/cadastro/cadastrar_carona'),
    routeBuilder: b3Builder,
  ),
  RouteEntity(
    key: 'carona/carona_home',
    uri: Uri.parse('carona/carona_home'),
    routeBuilder: b4Builder,
  ),
  RouteEntity(
    key: 'carona/visualizar/caronas_usuario',
    uri: Uri.parse('carona/visualizar/caronas_usuario'),
    routeBuilder: b5Builder,
  ),
  RouteEntity(
    key: 'carona/visualizar/carona_anterior',
    uri: Uri.parse('carona/visualizar/carona_anterior'),
    routeBuilder: b6Builder,
  ),
  RouteEntity(
    key: 'carona/visualizar/lista_carona_anterior',
    uri: Uri.parse('carona/visualizar/lista_carona_anterior'),
    routeBuilder: b7Builder,
  ),
  RouteEntity(
    key: 'carona/visualizar/[id]/carona',
    uri: Uri.parse('carona/visualizar/[id]/carona'),
    routeBuilder: b8Builder,
  ),
  RouteEntity(
    key: 'mensagem',
    uri: Uri.parse('mensagem'),
    routeBuilder: b9Builder,
  ),
  RouteEntity(key: 'rota', uri: Uri.parse('rota'), routeBuilder: b10Builder),
  RouteEntity(
    key: 'usuario/cadastro/cadastrar_carro',
    uri: Uri.parse('usuario/cadastro/cadastrar_carro'),
    routeBuilder: b11Builder,
  ),
  RouteEntity(
    key: 'usuario/cadastro/cadastrar_foto',
    uri: Uri.parse('usuario/cadastro/cadastrar_foto'),
    routeBuilder: b12Builder,
  ),
  RouteEntity(
    key: 'usuario/cadastro/cadastrar_localizacao',
    uri: Uri.parse('usuario/cadastro/cadastrar_localizacao'),
    routeBuilder: b13Builder,
  ),
  RouteEntity(
    key: 'usuario/cadastro/cadastrar_papel',
    uri: Uri.parse('usuario/cadastro/cadastrar_papel'),
    routeBuilder: b14Builder,
  ),
  RouteEntity(
    key: 'usuario/editar/editar_carro',
    uri: Uri.parse('usuario/editar/editar_carro'),
    routeBuilder: b15Builder,
  ),
  RouteEntity(
    key: 'usuario/editar/editar_perfil',
    uri: Uri.parse('usuario/editar/editar_perfil'),
    routeBuilder: b16Builder,
  ),
];

const routePaths = (
  path: '/',
  auth: (
    path: '/auth',
    login: '/auth/login',
    registrar: '/auth/registrar',
    senha: (path: '/auth/senha', esqueciSenha: '/auth/senha/esqueci_senha'),
  ),
  carona: (
    path: '/carona',
    cadastro: (
      path: '/carona/cadastro',
      cadastrarCarona: '/carona/cadastro/cadastrar_carona',
    ),
    caronaHome: '/carona/carona_home',
    visualizar: (
      path: '/carona/visualizar',
      caronasUsuario: '/carona/visualizar/caronas_usuario',
      caronaAnterior: '/carona/visualizar/carona_anterior',
      listaCaronaAnterior: '/carona/visualizar/lista_carona_anterior',
      $id: (
        path: '/carona/visualizar/[id]',
        carona: '/carona/visualizar/[id]/carona',
      ),
    ),
  ),
  mensagem: '/mensagem',
  rota: '/rota',
  usuario: (
    path: '/usuario',
    cadastro: (
      path: '/usuario/cadastro',
      cadastrarCarro: '/usuario/cadastro/cadastrar_carro',
      cadastrarFoto: '/usuario/cadastro/cadastrar_foto',
      cadastrarLocalizacao: '/usuario/cadastro/cadastrar_localizacao',
      cadastrarPapel: '/usuario/cadastro/cadastrar_papel',
    ),
    editar: (
      path: '/usuario/editar',
      editarCarro: '/usuario/editar/editar_carro',
      editarPerfil: '/usuario/editar/editar_perfil',
    ),
  ),
);
